---
version: "3.9"
services:
  worker:
    image: omarkhd/litess:latest
    entrypoint: ./worker
    ports:
      - 33060:3000
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 128M
  prometheus:
    image: prom/prometheus:v2.23.0
    volumes:
      - ./__scripts__/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.3.6
    volumes:
      - ./__scripts__/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./__scripts__/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/litess.yml:ro
      - ./__scripts__/grafana/litess.json:/var/lib/grafana/dashboards/litess.json:ro
      - ./__scripts__/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - 3000:3000
