{
 "title": "litess",
 "time": { "from": "2020-12-21T23:24:20.018Z", "to": "2020-12-21T23:49:35.807Z" },
 "panels": [
  { "title": "worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"litess\", service=\"worker\"}[10s]) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"litess\", service=\"worker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Engine Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(db_errors{\n  job=\"litess\", service=\"worker\"\n}[15s])) by (procedure)\n/\nsum(irate(db_queries_count{\n  job=\"litess\", service=\"worker\"\n}[15s])) by (procedure)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Engine QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(db_queries_count{\n  job=\"litess\", service=\"worker\"\n}[15s])) by (procedure)",
     "legendFormat": "{{ procedure }}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(db_queries{\n  job=\"litess\", service=\"worker\", procedure=\"query\"\n}) by (quantile)",
     "legendFormat": "{{procedure }} p{{ quantile }}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max(db_queries{\n  job=\"litess\", service=\"worker\", procedure=\"exec\"\n}) by (quantile)",
     "legendFormat": "{{procedure }} p{{ quantile }}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"litess\", service=\"worker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}